# .render.yaml
services:
  - type: web
    name: telegram-auto-approver-bot
    env: python
    branch: main                # ← the branch to watch
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
